### ISSUE TITLE
Tutorial for Integrating ArgoCD with Keptn

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn.github.io#449] opened 2020-02-27 13:36 UTC

**Comment by agrimmer** [comment] 2020-03-31 05:36
Currently, we are facing problems where Argo CD gets stuck in a "Suspended" state. 
In order to reproduce this problem, only Argo CD and Rollout need to be installed on the cluster.

**Setup Environment:**
`kubectl create namespace sockshop-production`
 
`argocd app create --name carts-production --repo https://github.com/my-keptn-tests/sockshop.git --dest-server https://kubernetes.default.svc --dest-namespace sockshop-production --path carts/argo/carts --revision production --sync-policy none`
 
**Steps:**
1.) Set 0.10.1 as image in https://github.com/my-keptn-tests/sockshop/blob/production/carts/argo/carts/values.yaml
2.) `argocd app sync carts-production`
3.) `kubectl argo rollouts promote  carts-production -n sockshop-production`
 
4.) Set 0.10.2 as image in https://github.com/my-keptn-tests/sockshop/blob/production/carts/argo/carts/values.yaml
5.) `argocd app sync carts-production`
6.) `kubectl argo rollouts abort  carts-production -n sockshop-production`
 
7.) Set 0.10.3 as image in https://github.com/my-keptn-tests/sockshop/blob/production/carts/argo/carts/values.yaml
8.) `argocd app sync carts-production`
---> Status of Rollout: Progressing, Suspended

**Comment by agrimmer** [comment] 2020-04-20 12:50
The problem above can be fixed by not using a hook with `argocd.argoproj.io/hook: PostSync` but with `argocd.argoproj.io/hook: Sync`.

**Comment by agrimmer** [comment] 2020-04-23 05:57
This PR https://github.com/keptn/keptn.github.io/pull/456 closes this issue.

**Comment by oleg-nenashev** [comment] 2022-01-21 13:23
Reopening it, because the last published version is for 0.7.x which is old and obsolete

**Comment by partmor** [comment] 2022-03-27 09:12
Hi! I'm new to Keptn, and am already using argo-cd as gitops-based CD tool, and wanted to continue with it instead of switching to keptn's helm-service. 

The currently published tutorials in the keptn documentation only use helm-service for CD.
However I've seen #456 (an archived tutorial) covers precisely this for an old version of keptn.

My question is: is there anything fundamentally wrong with this archived tutorial that cannot be reproduced for keptn 0.13?

My guess is that the main effort would be refactoring the webhook `Job` resource to be compatible with the most recent API? is there anything I'm missing?

Thank you in advance

**Comment by christian-kreuzberger-dtx** [comment] 2022-03-29 11:04
Keptn has changed fundamentally with Keptn 0.8.x, so it will not work

**Comment by partmor** [comment] 2022-03-30 18:08
> Keptn has changed fundamentally with Keptn 0.8.x, so it will not work

is there a way around it? any high level guidelines?

or is Keptn just not intended to work with Argo CD at this stage?

**Comment by agardnerIT** [comment] 2022-06-15 05:36
For everyone who (like me) hits this page. Keptn works perfectly with ArgoCD: https://www.youtube.com/watch?v=fEiauT1OzTE

Overview video contains GitHub repos at the end.

**Closed** 2023-03-27 11:18 UTC
